import type { Metadata } from "next";
import "../styles/globals.scss";
import { inter, jaka, workSans } from "@/fonts";
import StateContextProvider from "@/context/StateCtx";

export const metadata: Metadata = {
  title: "Nigeria Police Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StateContextProvider>
        <body
          className={`${inter.variable} ${jaka.variable} ${workSans.className}`}
        >
          {children}
        </body>
      </StateContextProvider>
    </html>
  );
}
